name: Artifact Demo

on: push

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create file
        run: echo "Hello DevOps" > hello.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-file
          path: hello.txt"
           
         

