name: Hello Workflow

on:
 push:
  branches:
     - main
     - developer

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Triggered by ${{ github.actor }}"
           
         

