name: Matrix Demo

on: push

jobs:
  matrix-test:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [16,18]

    runs-on: ${{ matrix.os }}

    steps:
      - run: echo "OS ${{ matrix.os }} Node ${{ matrix.node }}"
           
         

